### ISSUE TITLE
EPG source URL's changing?

### ISSUE THREAD

**Issue by geonsey** [matthuisman/i.mjh.nz#1]
Hey Matt. Just saw that you moved to Github. Does that mean that you are discontinuing your website https://i.mjh.nz/
and we will need to change the URL to the EPG sources? 

Example: https://i.mjh.nz/SamsungTVPlus/all.xml (currently) to github source: https://github.com/matthuisman/i.mjh.nz/blob/master/SamsungTVPlus/all.xml

**Comment by matthuisman** [comment]
yeh, CF wasnt happy.
pretty sure i can just keep the i.mjh.nz urls redirecting.
