### ISSUE TITLE
Australia Channel 10 stream not working

### ISSUE THREAD

**Issue by treetrum** [matthuisman/i.mjh.nz#10]
Hi, apologies if this is out of your control... TBH I'm a bit confused what the service this site provides _is_.

For context, I use the [file here](https://raw.githubusercontent.com/matthuisman/i.mjh.nz/master/au/Sydney/raw-tv.m3u8) in addition to https://github.com/tellytv/telly to get my Plex server to have access to local broadcast TV.

At some point (sorry, can't event tell you when) "Channel 10" stopped working (I get "Failed to stream" style errors). I've tried testing out various regions outside of Sydney and they all seem to fail with the same results. 

I've tried cutting out the middle man and opening the [m3u8 stream](https://i.mjh.nz/au/Sydney/tv.101406020625.m3u8) directly in VLC player and again, 10 will not play.

Any help here would be greatly appreciated!

**Comment by treetrum** [comment]
Just found this comment over on Whirlpool, seems related and to do with DAI. But I can see you're fairly across those Whirlpool forums ;) 

Am I out of luck here and 10 has just broken IP streams for my use case?

**Comment by matthuisman** [comment]
for starters, are you physically in Australia? 10 blocks lots of vpns.
Also, are you using an ad blocker? either on device or on network level?

**Comment by treetrum** [comment]
Yep — physically in Australia. 
No adblockers on the network.
Plex server is an UNRAID box, client is an Apple TV. Neither of which have adblockers installed.

Signing in to the https://10play.com.au/live/ten website allows me to stream from them directly — so don't think I'm getting geo-blocked.

**Comment by matthuisman** [comment]
just tried in kodi and it plays. so i suspect the issue is SSAI and whatever player your using not supporting that

**Comment by treetrum** [comment]
No worries — I'll keep looking into it. See if I can manipulate ffmpeg to do what I need. Maybe need to look into running Kodi instead hah.

**Comment by matthuisman** [comment]
looking at VLC debug log, it gets a 404 for https://net10-livestream-keys.play.cbsi.video:443/10NSW/key/K81700.key
So I suspect they are blocking VLC user-agent

Try changing the user-agent of the program your using to a web user-agent (this is what my kodi addon does).
eg
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36

**Comment by matthuisman** [comment]
aha, success (in VLC)
![image](https://user-images.githubusercontent.com/6225961/152944841-56168cf9-10b2-489a-bbed-74b8c785e58e.png)

**Comment by matthuisman** [comment]
you may still have issues at adbreaks tho due to x-discontinuity

**Comment by treetrum** [comment]
Thanks so much — I've gotten it working directly with ffmpeg from the command line by modifying the user agent. I should be able to take it from here :D Appreciate it!

**Comment by matthuisman** [comment]
sneaky 10! 
blocking the key url makes it quite hard to tell why its failing

**Comment by speedst3r** [comment]
I'm getting this problem in tvheadend using the iptv_merge.m3u8.sh script which implements a custom user-agent, set the log level to debug and was getting a HTTP 410 error.

https://pastebin.com/B8YL0mr2

**Comment by matthuisman** [comment]
@speedst3r 
as far as I can tell, the issue is on 10's side. I can't even get live streaming working on there website
