### ISSUE TITLE
ABC Me / TV Plus changes

### ISSUE THREAD

**Issue by matthuisman** [matthuisman/i.mjh.nz#102]
https://tvtonight.com.au/2024/06/farewell-to-abc-me-abc-tv-plus.html

**Comment by oismacca** [comment]
Looks like there's 4 additional livestreams now too. 100% Faves, Cartoons, Family Faves and BTN.

**Comment by matthuisman** [comment]
ABC Me renamed to ABC Entertains
ABC TV Plus renamed to ABC Family

**Comment by matthuisman** [comment]
ill create a new ticket for adding the FAST channels
