### ISSUE TITLE
Adelaide AU stations

### ISSUE THREAD

**Issue by hemiceni** [matthuisman/i.mjh.nz#106]
Hi I would appreciate having Three D radio added to the Adelaide list. 
http://sounds.threedradio.com:8000/stream.m3u or https://www.threedradio.com/about/ways-to-listen/

Additionally there's a few of the big radio stations missing from the Adelaide list

-Nova 919 https://novafm.com.au/station/nova919
-Triple M https://www.play.listnr.com/station/mmm-adelaide?referrer=triplem
-SAFM https://www.play.listnr.com/station/hit-adelaide

Thank you

**Comment by matthuisman** [comment]
thanks. they all should be available within the next hour :)
