### ISSUE TITLE
Stirr EPG and PBS

### ISSUE THREAD

**Issue by ChiFungLam** [matthuisman/i.mjh.nz#107]
Hello all,

        I am using Tivimate to import the Stirr m3u8 and EPG (tried all.xml.gz and all.xml) but no EPG load ? The Plex EPG can load without any problem. Also, PBS now need Widevine ? What should I install in order to watch it ? Or it only work in Kodi ? Thanks.

Regds
LAM Chi-fung

**Comment by matthuisman** [comment]
youll need to ask tivimate if they support widevine m3u8s with "kodi style properties" for PBS

stirr EPG seems fine to me:
https://i.mjh.nz/Stirr/all.xml

**Comment by ChiFungLam** [comment]
Eventually I got the PBS work. There are 2 conditions:
1) support widevine, I check by: if this device can watch Disney+/Netflix, then it support widevine, if can't, sure not
2) VPN (since I live in Asia)

After I find a device fulfill the above 2 conditions, the PBS play. But Stirr EPG still not work ;<.....

**Comment by matthuisman** [comment]
"not work " is very unhelpful
Describe how youve setup the EPG, what urls and what isnt working

**Comment by ChiFungLam** [comment]
I import https://i.mjh.nz/Stirr/all.m3u8 as playlist and import https://i.mjh.nz/Stirr/all.xml.gz as EPG for Stirr (try https://i.mjh.nz/Stirr/all.xml as well, same result). After import everything, the Stirr channels can play but EPG not show (empty). For PBS, Plex etc the EPG show correctly.

**Comment by matthuisman** [comment]
oh. stirr has really rubbish epg at present.
eg. go try their website: https://stirr.com/live?channel_id=5442

I cant provide anything better than they do as thats where its sourced from/
I believe only some channels have epg, and even then seems to be wrong.

**Comment by ChiFungLam** [comment]
Actually I try browse Stirr's EPG with a text editor and find that content is there but only can't display in the IPTV player (in my case, Tivimate) and problem occurs since 18/19 June, the EPG is ok before that. ;<

**Comment by matthuisman** [comment]
i cant see any epg on there site. its all broken

**Comment by matthuisman** [comment]
i wont be investigating until their site is fixed

**Comment by ChiFungLam** [comment]
Agree, garbage in and garbage out. wait till the site fixed

**Comment by BoomGold23** [comment]
The Samsung + EPG seems to have problem as well, not all the time slots. For example, UK Samsung+, CNN channel, the EPG only updated to 9:00 AM (my local time) and now is 20:20 (my local time)
![Screenshot_20240627-201613](https://github.com/matthuisman/i.mjh.nz/assets/134958425/6316e490-de35-4c21-a7bb-8ef791d7c91e)

**Comment by ChiFungLam** [comment]
The Samsung + EPG seems to have problem as well, not all the time slots. For example, UK Samsung+, CNN channel, the EPG only updated to 9:00 AM (my local time) and now is 20:20 (my local time)
![Screenshot_20240627-201613](https://github.com/matthuisman/i.mjh.nz/assets/84639815/eb303e55-6960-4461-92a0-ac6d2843d761)

**Comment by matthuisman** [comment]
samsung should now be fixed

**Comment by ChiFungLam** [comment]
Samsung+ EPG work now., give EPG for coming 5 hrs (local time 11:00 AM and EPG show up to 4:00 PM)
