### ISSUE TITLE
Update PlutoTV to https

### ISSUE THREAD

**Issue by dxzdxz1** [matthuisman/i.mjh.nz#108]
As the title says, it's something small, PlutoTV domain supports https requests, but there are some links like this one:

https://r.mjh.nz/PlutoTV/5fd7bb1f86d94a000796e2c2-alt.m3u8
that redirects to http://stitcher-ipv4.pluto.tv/v1/...

Which I believe is exactly the way you extract them, but this breaks the usage of these specific streams on some browsers

**Comment by matthuisman** [comment]
have fixed that :) next pluto scrape (2-3 hours) will use https:// .
