### ISSUE TITLE
Source of SamsungTVPlus data

### ISSUE THREAD

**Issue by m-kloeckner** [matthuisman/i.mjh.nz#11]
Hi Matt!

Can you please give some background information on how you retrieve the raw SamsungTV Plus information und generate the information in the "SamsungTVPlus" folder?

I would like to understand how my Samsung TV fetches the TVPlus information. I guess you reverse-engineered the same Samsung URLs/APIs to generate the channel & EPG data.

Thanks!
Martin

**Comment by matthuisman** [comment]
I use the same api calls as there android Samsung phone app. That's why I
can't get all the channels that the tv does. It's slightly different
