### ISSUE TITLE
Foxtel Go - Unexpected error

### ISSUE THREAD

**Issue by RLR2379** [matthuisman/i.mjh.nz#110]
Had to reload/install Foxtel Go after a long time since using but now when logging in it says "Unexpected Error"
 Access Denied --> You dont have permission to access "http&#58:47**********.....on this server <P>
Login details are correct and sufficient licences available?  Has anyone else got issues logging into Foxtel GO?

**Comment by matthuisman** [comment]
https://github.com/matthuisman/slyguy.addons/issues/586
