### ISSUE TITLE
Roku missing

### ISSUE THREAD

**Issue by t7504** [matthuisman/i.mjh.nz#111]
Hello - 

Roku M3U8 has gone missing.

Thanks!

**Comment by gabbymouth** [comment]
Maybe you already know this, but you can just change the server name from the old one to the new one in each url and it will work. One global change with a text editor will do the trick.

**Comment by gabbymouth** [comment]
> Hello -
> 
> Roku M3U8 has gone missing.
> 
> Thanks!

Maybe you already know this, but you can just change the server name from the old one to the new one in each url and it will work. One global change with a text editor will do the trick.

**Comment by matthuisman** [comment]
back now
