### ISSUE TITLE
Australian Channel 9 streams not working

### ISSUE THREAD

**Issue by LGSAM59** [matthuisman/i.mjh.nz#113]
Hi , just trying to trouble shoot , I'm using the Australian playlist on Tivimate with DNS4ME here in NZ all had been working fine but 9now channels no longer work all others work like 7 and Ten . I can watch 9now live channels using the app . Seems to have failed today.

Love your work by the way .

**Comment by tehfonz** [comment]
Having the same issue here. 
tried the fix that works for ch7 & ch10:

```
#EXTM3U x-tvg-url="https://i.mjh.nz/au/Sydney/epg.xml.gz"

#EXTINF:-1 tvg-id="mjh-10-nsw" channel-id="mjh-10-nsw" tvg-logo="https://i.mjh.nz/.images/10-nsw.png" tvg-chno="10" group-title="Sydney" ,10
#EXTVLCOPT:http-user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
https://i.mjh.nz/10-nsw.m3u8
```

with the ch9 stuff:

```
#EXTM3U x-tvg-url="https://i.mjh.nz/au/Sydney/epg.xml.gz"

#EXTINF:-1 tvg-id="mjh-channel-9-nsw" channel-id="mjh-channel-9-nsw" tvg-logo="https://imageresizer.static9.net.au/MFJ65H8J3Itwr7-HcHQxr-jBssc=/768x0/vms-tv-images-prod.s3-ap-southeast-2.amazonaws.com%2F2015%2F11%2F11%2F9_Colour_RGB.png" tvg-chno="9" group-title="Sydney" , Channel 9
#EXTVLCOPT:http-user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
https://i.mjh.nz/channel-9-nsw.m3u8
```

Unfortunately no dice.
Wonder if this is hardening or ad injection for the Olympics :/

**Comment by JaxonPlays** [comment]
via 9now if you go to the live and monitor the network tab, you can download the stream vi yt-dlp hope this works as a temp fix

**Comment by matthuisman** [comment]
the 9now kodi addon still works as long as "use legacy streams" is disabled.

trying to fix the playlist streams now

**Comment by matthuisman** [comment]
ok. they disabled the old stream urls. 
Now have switched to the generated server side ad injection urls (same as the 9now addon)
Unfortunately, these types of streams can cause playback issues in various players - so see how you go

**Comment by JaxonPlays** [comment]
In NextPVR, the audio stops recording after the first ad break.

**Comment by polluxau** [comment]
this is no longer working again

**Comment by matthuisman** [comment]
Assume broken for now. I'm not going to keep cat and mouse with them. The
9now Kodi add-on works as doesn't use a shared token

**Comment by polluxau** [comment]
that works great thank you

**Comment by phoen88** [comment]
Looks like this is the reason why my custom setup I had for Nine (and that only ever worked for Nine) has now broken. Looks like I may need to try out the Kodi Add-on.

How do these new URLs work? I've never understood how they work and it was a pain to try and workaround. I do know the ABC (and I think Seven?) have had this for a while now.

**Comment by svetecs** [comment]
I know this issue is closed, but since Ch9 re-instated the old links, TiviMate spits out an 'IllegalException' error.  It can take changing away from Ch9 and back to it that the stream will start working.  Is there a dodgy streaming URL being presented that TiviMate doesn't like?

**Comment by phoenpc** [comment]
@svetecs https://github.com/matthuisman/i.mjh.nz/issues/116#issuecomment-2345700297

**Comment by matthuisman** [comment]
I'm going to close this thread to stop any more replies
