### ISSUE TITLE
Kayo EPG missing chunks of time

### ISSUE THREAD

**Issue by martinreedau** [matthuisman/i.mjh.nz#12]
Hi Matt,

The Kayo (and Foxtel) EPGs are missing large chunks of time, usually around 24 hours worth at a time. To demonstrate I grepped a single channel and annotated the start dates - [kayo-epg-grep.txt](https://github.com/matthuisman/i.mjh.nz/files/8134497/kayo-epg-grep.txt). You'll see entire days missing, usually including the following day.

Thanks!

**Comment by matthuisman** [comment]
please try now and let me know

**Comment by martinreedau** [comment]
Looks good, thanks!
