### ISSUE TITLE
Samsung TV Plus Brazil channels

### ISSUE THREAD

**Issue by bracarino** [matthuisman/i.mjh.nz#120]
Hi,

Can you add Samsung TV Plus Brazil channels?
They have Caze TV, which is broadcasting Paris 2024 Olympic Games, among other interesting channels.

Thank you

**Comment by matthuisman** [comment]
see the "Region / channels missing" section here:
https://www.matthuisman.nz/2021/06/samsung-tv-plus-kodi-add-on.html

**Comment by bracarino** [comment]
Thank you!
