### ISSUE TITLE
tvh-tv.m3u8 - Tvheadend fails to scan some 7 network muxes

### ISSUE THREAD

**Issue by its-wizza** [matthuisman/i.mjh.nz#121]
Using https://i.mjh.nz/au/Canberra/tvh-tv.m3u8 as an IPTV automatic network in Tvheadend

**Seven, 7two, 7mate, 7 NEWS Spotlight, 7AFL** all fail to scan, while **7flix, 7Bravo, 7now** work; i.e.:
![image](https://github.com/user-attachments/assets/07e17a9a-ddd3-45b3-b4b0-10a2a98a22d7)

Example mux url for Seven:
`pipe://ffmpeg -loglevel fatal -probesize 10M -analyzeduration 0 -fpsprobesize 0 -headers user-agent:\ Mozilla/5.0\ (Windows\ NT\ 10.0;\ Win64;\ x64)\ AppleWebKit/537.36\ (KHTML,\ like\ Gecko)\ Chrome/98.0.4758.102\ Safari/537.36\r\nseekable:\ 0\r\nreferer:\ \ \r\n -i https://i.mjh.nz/seven-syd.m3u8 -vcodec copy -acodec copy -metadata service_name=mjh-seven-syd -f mpegts pipe:1`

Output in Tvheadend log if I set scan status to PEND:
```
2024-08-09 14:43:47.552 mpegts: tvh-tv.m3u8 - Seven in IPTV Automatic Network - MJH Canberra - tuning on IPTV #1
2024-08-09 14:43:47.556 spawn: Executing "/usr/bin/ffmpeg"
2024-08-09 14:43:47.556 subscription: 001C: "scan" subscribing to mux "tvh-tv.m3u8 - Seven", weight: 6, adapter: "IPTV #1", network: "IPTV Automatic Network - MJH Canberra", service: "Raw PID Subscription"
2024-08-09 14:43:52.552 mpegts: tvh-tv.m3u8 - Seven in IPTV Automatic Network - MJH Canberra - scan no data, failed
2024-08-09 14:43:52.552 subscription: 001C: "scan" unsubscribing
```

Actual m3u8 (https://i.mjh.nz/seven-syd.m3u8) plays fine in VLC

Running ffmpeg command on Tvheadend machine writes raw output to terminal

Tvheadend config screenshots:
![image](https://github.com/user-attachments/assets/3f514293-fa4f-4fbd-8503-51ccbdeff670)
![image](https://github.com/user-attachments/assets/9726cc07-3058-4973-8df7-1f6262594de3)

Is there any further tweaking to Tvheadend config to allow the mux to scan?

Thanks

**Comment by matthuisman** [comment]
Might need to try longer time-outs etc. I haven't used tvheadend in some
time but I remember could be fussy

**Comment by its-wizza** [comment]
Thanks Matt, you were correct. 

IPTV Automatic Network > Edit > Advanced Settings > Maximum timeout (seconds)
Changed this value to 10 (from default 0), this allowed channel scan to be OK. 
5 seconds was enough for 7AFL but not for Seven.

Not related, but interested in if you personally use an alternative to Tvheadend for PVR? Just starting to get into the world of IPTV, if there is something less janky than Tvheadend I'd love to try that instead

**Comment by matthuisman** [comment]
Yah. I don't really watch or use any of the stuff I build. As I'm too busy
building it all. But I enjoy doing that so ya know :) if I wanna watch live
stuff, I'll just use my kodi IPTV addon's. I used to use tvheadend with UHF
antenna though

**Comment by matthuisman** [comment]
I still think tvheadend is the better way to do it all. I just don't have a
need for it :)
