### ISSUE TITLE
All SBS Channels now 403. Appear to have gone the way of Nine's?

### ISSUE THREAD

**Issue by Goatlips70** [matthuisman/i.mjh.nz#122]
SBS channels are all 403 this afternoon. From my (very limited) understanding of the issue with Nine they now requiring a unique user ID / token ? Have SBS followed suit? Are we entering a new and dark era?

**Comment by matthuisman** [comment]
Let's not jump to conclusions (mat)

**Comment by Goatlips70** [comment]
Well, I did say my understanding was limited :-) Jumping to conclusions is some of my best work.

**Comment by matthuisman** [comment]
issue was me server was running out of memory and never publishing the updated url. nothing to do with sbs
