### ISSUE TITLE
Samsung Plus TV - UK playlists, missing channels?

### ISSUE THREAD

**Issue by wkc-lang** [matthuisman/i.mjh.nz#124]
Hi, the UK playlists are missing the 'Entertainment Hub' and 'Sky Mix' channels. However both are listed in the UK epg. Is this something that maybe resolved? Thanks.

**Comment by matthuisman** [comment]
they both will be widevine channels so unable to be played

**Comment by matthuisman** [comment]
you can see them in https://i.mjh.nz/SamsungTVPlus/app.json but they have license_url which means they are widevine and not possible to be played.  In future, i may be able to get them to work in Kodi but not possible yet.

**Comment by joseph23pronton** [comment]
but does that mean that they will gonna use mpd from now on? or still m3u8?
