### ISSUE TITLE
Matt Can you put the json back online will be great thanks 

### ISSUE THREAD

**Issue by openn1** [matthuisman/i.mjh.nz#128]
Matt Can you put the json back online will be great thanks 

https://i.mjh.nz/SamsungTVPlus/app.json

Thanks!

If you need help serve coding etc let me know!

**Comment by matthuisman** [comment]
please update the docker container to latest :)

**Comment by openn1** [comment]
I dont have docker only from you page use the https://i.mjh.nz/SamsungTVPlus/app.json ;-)

**Comment by matthuisman** [comment]
add a . in front of app

**Comment by openn1** [comment]
how you mean ?

**Comment by matthuisman** [comment]
https://i.mjh.nz/SamsungTVPlus/.app.json
