### ISSUE TITLE
Matt can you add Netherlands nl

### ISSUE THREAD

**Issue by openn1** [matthuisman/i.mjh.nz#129]
Matt can you add Netherlands nl

you know where ;-)

**Comment by matthuisman** [comment]
not unless netherlands can use the official android mobile app

see "region / channels missing" here:
https://www.matthuisman.nz/2021/06/samsung-tv-plus-kodi-add-on.html

**Comment by openn1** [comment]
Thanks Matt i know. but not everyone has the knowledge of that. so if you add it where we al ready discussed about it will be verry nice.

thanks Matt

**Comment by matthuisman** [comment]
your not reading correctly. **I CAN NOT add it until their android mobile app supports it**

**Comment by openn1** [comment]
ok thats clear thanks Matt and thanks for all the thing you do.
