### ISSUE TITLE
Season/Episode numbers in EPG

### ISSUE THREAD

**Issue by Ado77** [matthuisman/i.mjh.nz#13]
Hey Matt,

Any chance you could add the season/episode numbers to the EPGs? I cant find a repo that you use to generate the guides. I'd happily make the change (assuming it's possible) and make a PR.

Thanks

**Comment by matthuisman** [comment]
For what epg?
99% sure that info won't be available using the endpoints I use currently

**Comment by Ado77** [comment]
I was looking at Sydney in particular...

**Comment by matthuisman** [comment]
Oh yeh. The source I use has very limited data. Have a Google, pretty sure
there are better Australia epgs available

**Comment by Ado77** [comment]
yeah, but correct me if I'm wrong, they wont tie into your playlists as the ids wont match...

**Comment by matthuisman** [comment]
sorry, forgot to reply.

If you find a good EPG, let me know.
I may be able to start using it and edit my m3u8's to match

**Comment by Ado77** [comment]
Hey, no worries. I landed up using this for Sydney:

http://xmltv.net/xml_files/Sydney.xml

They have a whole bunch of regions and countries. I landed up using that in xTeVe straight into plex... I'll try it all out over this week and see how it goes.

**Comment by matthuisman** [comment]
ive made progress on my complete re-work of my IPTV system.

You can watch the progress below:
https://new.mjh.nz/
