### ISSUE TITLE
Issue with https://i.mjh.nz/tvnz-1.m3u8

### ISSUE THREAD

**Issue by SethL** [matthuisman/i.mjh.nz#130]
I'm getting 403 errors in Channels now with NZ tv feeds.  I get some channels but not the main ones like TVNZ1, TVNZ2, etc.  I'm using smartdns and have all of my traffic appearing to come from NZ.  It worked fine a few days ago and I haven't changed anything.  Could this be the same issue as AU Channel 9 you think?

`2024/08/23 09:27:28.160205 [ERR] Failed to start stream for ch1: M3U: Could not fetch playlist from i.mjh.nz: GET: https://i.mjh.nz/tvnz-1.m3u8: 403 Forbidden`

`2024/08/23 09:27:28.170533 [HLS] Couldn't generate stream playlist for ch1-dANY-ip172.16.1.11: M3U: Could not fetch playlist from i.mjh.nz: GET: https://i.mjh.nz/tvnz-1.m3u8: 403 Forbidden`

**Comment by matthuisman** [comment]
TVNZ have most likely blocked your smart dns proxy IP address.
Confirm by trying the streams directly on the TVNZ website

**Comment by SethL** [comment]
Yeah that was it thanks
