### ISSUE TITLE
Roku Plugin - EPG bug

### ISSUE THREAD

**Issue by davidmguest** [matthuisman/i.mjh.nz#131]
Matt, the EPG is not working for the new Roku addon.
There is a mismatch between the tvg_id used by the addon and that used in the epg.xml.
The addon uses just the id (eg 'eb1dbd690001553eacdf32d7b155b933') whilst the epg adds a prefix of 'roku-' (eg 'roku-eb1dbd690001553eacdf32d7b155b933')
Manually changing the epg-id  for each channel in iptvmerge makes the epg work.

**Comment by matthuisman** [comment]
oh thanks. The next generated EPG will have the ids without roku- prefix :)
