### ISSUE TITLE
Missing epg.xml in the mirror

### ISSUE THREAD

**Issue by felipehertzer** [matthuisman/i.mjh.nz#132]
Hey @matthuisman,

I've noticed that the bot seems to have stopped generating the EPG.XML file. [https://i.mjh.nz/au/all/epg.xml](https://i.mjh.nz/au/all/epg.xml).

Thanks!

**Comment by matthuisman** [comment]
only doing xml.gz now due to storage issues with github as per https://github.com/matthuisman/i.mjh.nz/issues/127#issuecomment-2316262789

**Comment by felipehertzer** [comment]
Thanks @matthuisman, I've moved to GZ and it works great, thank you for the support.

**Comment by matthuisman** [comment]
excellent, can you advise what software your using?
Im trying to find anything that does not support gz

**Comment by felipehertzer** [comment]
I'm using on IPTV Pro for Android and also on Laravel PHP (Http::get) to alert me about programs that I want to watch.

**Comment by matthuisman** [comment]
Ok sweet. Good to know they support gz
