### ISSUE TITLE
Matt .json offline

### ISSUE THREAD

**Issue by openn1** [matthuisman/i.mjh.nz#133]
Dear Matt is the .json offline?
https://i.mjh.nz/SamsungTVPlus/.app.json

Greatings

**Comment by matthuisman** [comment]
back now

**Comment by openn1** [comment]
thanks it working

**Comment by yuyutsu07** [comment]
> Dear Matt is the .json offline? https://i.mjh.nz/SamsungTVPlus/.app.json
> 
> Greatings

How to use this ?
