### ISSUE TITLE
Channel 7 Iptv 

### ISSUE THREAD

**Issue by nvscheeko** [matthuisman/i.mjh.nz#135]
Hi mate 

Recently watching Channel 7 about 20-30 mins it will loose stream, No other channels seems to be affected but comes back on in another 15 or so. 

I have seen this while watching and also on recording, All other channels are fine and record file from the Kodi M3u8 https://i.mjh.nz/au/Brisbane/kodi-tv.m3u8

Should mention using HLS on Channels DVR (Get Channels Server) via Nvidia Shield

Maybe i can try another file?

**Comment by matthuisman** [comment]
Are you watching in Kodi?

**Comment by nvscheeko** [comment]
Hi Matt Via Nvidia Shield with the File uploaded to Get Channels Server on Windows server so the PC hosts the files Shield just front end.

**Comment by matthuisman** [comment]
Oh right. I'm not sure sorry. Maybe ask on the get channels forum. They may
have some ideas

**Comment by nvscheeko** [comment]
Thanks Matt no problem ill try on Live channels direct on Shield, Its weird no other channels do it could it be something with adds or something

**Comment by nvscheeko** [comment]
Thanks again for reply and hard work, Close this Issue
