### ISSUE TITLE
TVNZ OnDemand Installation Error

### ISSUE THREAD

**Issue by gyCfjSnO** [matthuisman/i.mjh.nz#138]
Unable to install TVNZ OnDemand for Android TV using https://f.mjh.nz/apk/tvnz-atv-6.2.2.apk

APKMirror Installer
> App installation failed. The new package requires at least one split and it was not provided.

Package Installer 
> This app isn't compatible with your TV.

Device is a Google TV Streamer 4K running Android 14.

**Comment by matthuisman** [comment]
try this: https://f.mjh.nz/apk/tvnz-atv-6.3.0.zip

You'll need use Xplore or some other app that can install split apks
