### ISSUE TITLE
Cannot combine some EPGs

### ISSUE THREAD

**Issue by ls-milkyway** [matthuisman/i.mjh.nz#139]
I was able to combine 3 EPGs using [tv_merge](https://manpages.ubuntu.com/manpages/jammy/man1/tv_merge.1p.html) :
1) https://i.mjh.nz/SamsungTVPlus/all.xml
2) https://i.mjh.nz/PlutoTV/all.xml
3) https://i.mjh.nz/Plex/all.xml

but the last https://i.mjh.nz/Stirr/all.xml is not compatible with above 3 combined and tv_merge (only reliable program) throws array related error at line 180 of [the code](https://github.com/XMLTV/xmltv/blob/master/filter/tv_merge)

What I have tried?
1) Used tv_sort
2) Tried some other tv xml mergers.

Can you find and rectify the issue?

**Comment by matthuisman** [comment]
No sorry. That's not my merge program

**Comment by matthuisman** [comment]
Your best to ask the developer of that script

**Comment by matthuisman** [comment]
If you look at the stirr epg, it's empty anyway. There are no programs. That's probably the issue. Stirr don't really publish an epg anymore
