### ISSUE TITLE
Channel 9 (AU) not importing into TVH

### ISSUE THREAD

**Issue by yolk3d** [matthuisman/i.mjh.nz#140]
Using: TVHeadend + Jellyfin - both in docker containers on Synology NAS.

Issue: Channel 9 Brisbane shows in the THV m3u8 code from the 2017 blog ( https://i.mjh.nz/au/Brisbane/tvh-tv.m3u8 ), however TVheadend is not creating a channel from it. If I used the Kodi links from 2019 blog, it shows, however no audio. Other 9 associated channels work.

Sent you some coffee money.

**Comment by matthuisman** [comment]
when you into tvheadend can you see it? is it just failing to scan in?

**Comment by Australis86** [comment]
I may be experiencing something similar (not sure if it's the same problem), with both the Melbourne-region Channel 7 and 9 groups failing to scan in TVHeadEnd (running on a Raspberry Pi). The ABC, 10 and SBS groups all scan successfully and can be viewed.

Is there an issue with the 7 and 9 streams?

**Comment by yolk3d** [comment]
> when you into tvheadend can you see it? is it just failing to scan in?

it’s not showing up in tvheadend. The kodi files show up for channel 9 but no sound.  I’ll try @Australis86 suggestion to increase timeout.
