### ISSUE TITLE
All SBS Channels getting error 403

### ISSUE THREAD

**Issue by kanesbit** [matthuisman/i.mjh.nz#141]
Hello Matt

as of this morning (6/10) all SBS channels are erroring out with error 504

I’ve confirmed the streams work via the SBS app

I’m using Tivimate, and all other streams are working fine 

No user agent or UDP proxy set 

have SBS recently added any additional authentication requirements?

**Comment by kanesbit** [comment]
Grrr. Typed this on my phone. Error 403, as in "forbidden", ignore the 504 reference

**Comment by cdvreede** [comment]
same issue here - using TVH on a Pi - IPTV-AU kodi addon also not working...

**Comment by matthuisman** [comment]
SBS channels are back now
