### ISSUE TITLE
Channel 7 - Kodi

### ISSUE THREAD

**Issue by JaxonPlays** [matthuisman/i.mjh.nz#143]
Seems that the quality never increases stuck at 288p.

**Comment by matthuisman** [comment]
Look into the inputstream.adaptive addon settings for quality

Alternatively, slyguy supporters get access to quality select / force (https://www.matthuisman.nz/2024/01/supporter-perks.html)
https://www.matthuisman.nz/2019/09/new-quality-select-in-my-add-ons.html
