### ISSUE TITLE
Channel 7 - Quality

### ISSUE THREAD

**Issue by JaxonPlays** [matthuisman/i.mjh.nz#144]
Hi there,

It seems that the links have changed randomly.

It used to be this which provided 1080p 50fps
https://npc.cdn.7livecloud.io/hls/live/SYD1/master.m3u8

And now it's changed to this domain which provides 720p 25fps
csm-e-n7aus-eb.tls1.yospace.com

Can this change be reverted? I like my quality.

**Comment by matthuisman** [comment]
No sorry. That 1080 url includes some other cdn which often doesn't work
which breaks playback for others

**Comment by matthuisman** [comment]
one option is to host a copy of that file myself with the tbs cdn urls removed

**Comment by matthuisman** [comment]
do you know anwhere that 7 actually exposes 1080 streams?
Looks like all their official website / apps are 720

**Comment by JaxonPlays** [comment]
Might be for TV App? Not quite sure but that domain has been floating around for years and works and is also the same domain as their live subtitle captions.

**Comment by JaxonPlays** [comment]
Yeah, I’m finding with the new server with an example such as NextPVR, it fails to record when an Ad Break starts.

**Comment by matthuisman** [comment]
Yes, that'll be because yospace urls typically do server side ad injection. Using direct playlists don't..

But again, the tbs cdn had issues recently and sometimes it's sub url is listed before the npc urls which breaks players that don't just try the next url

**Comment by matthuisman** [comment]
ok. wrote a quick service to grab the 7livecloud playlists, strip the npc cdn and then save them to my server
my urls now point to those files

**Comment by matthuisman** [comment]
See
https://github.com/matthuisman/i.mjh.nz/issues/167#issuecomment-2680170726
