### ISSUE TITLE
Melbourne (AU) Channels not working

### ISSUE THREAD

**Issue by svetecs** [matthuisman/i.mjh.nz#145]
None of the Melbourne FTA channels work.  Curiously, other states FTA work fine. 

Also, all the FTA channels in Tivimate give a 404 error.  In Implayer, all the channels work, except for Melbourne.

**Comment by cdvreede** [comment]
bit weird - I can get all stations except for channel 9 itself (after reconfiguring TVHeadend) - but it takes a very long time for the stream to start. the Channel 9 stream seems to timeout...

**Comment by svetecs** [comment]
Weird indeed.  I installed Tivimate on my android phone and the same 404 errors exist like they do on my CCWGTV.

But on IMPlayer, those same channels (except for Melbourne) work fine.

**Comment by svetecs** [comment]
All good.  I curate my playlists using IPTVBoss and it seems as though some of the AU channels had changed in someway from mjh.  I updated those and all FTA is working well now.

**Comment by matthuisman** [comment]
oh. maybe you didn't see my twitter / reddit post:

https://x.com/MattHuismanNZ/status/1846463437075038365
https://www.reddit.com/r/MattHuisman/comments/1g4udje/mjhnz_stream_urls_have_changed/

**Comment by cdvreede** [comment]
Thnx mate – great job!!!

 

Lost a bit of track on what resultion the IPTV channels are these days. I know 9 is 1080P as is ABC and I believe SBS?? Now with 7 also going 1080P its only 10 that still is better through FTA/Antenna??

 

thnx

 

Dennis de Vreede

M:  <tel:+61%20414998673> +61 414998673

E:  ***@***.***> ***@***.***
