### ISSUE TITLE
Channel 10 au IPTV not working

### ISSUE THREAD

**Issue by tehfonz** [matthuisman/i.mjh.nz#146]
The Channel 10 AU IPTV m3u8 file is not working.
I have tried a number of different files (raw, kodi, tvh) & regions (Sydney, Brisbane, Adelaide, Canberra) to get it working but they all refuse to play. That's for 10, Peach, Bold.
The 10play Kodi addon works fine though

**Comment by matthuisman** [comment]
so the 10 channels via IPTV AU Kodi add-on also don't work for you?

**Comment by tehfonz** [comment]
10 IPTV via the Kodi Add-ons works fine!

**Comment by matthuisman** [comment]
So where doesn't it work? What player? I suggest it's a user agent header
that may need to be set etc

**Comment by tehfonz** [comment]
I'm using NextPVR with & without the kodi/agent header it seems to fail.

**Comment by matthuisman** [comment]
Try user agent okhttp   that's what I use in my Kodi playlists / addon's

**Comment by tehfonz** [comment]
Sorry for my ignorance, but how do I properly format the following m3u8 file to use the okhttp user-agent:
I've tried searching I cant find a proper / supported way to format it.
```
#EXTINF:-1 tvg-id="mjh-10-nsw" channel-id="mjh-10-nsw" tvg-logo="https://i.mjh.nz/.images/10-nsw.png" tvg-chno="10" group-title="Sydney" ,10

#EXTVLCOPT:http-user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
https://i.mjh.nz/10-nsw.m3u8
```

I tried:

```
#EXTINF:-1 tvg-id="mjh-10-nsw" channel-id="mjh-10-nsw" tvg-logo="https://i.mjh.nz/.images/10-nsw.png" tvg-chno="10" group-title="Sydney" ,10

#EXTVLCOPT:http-user-agent=okhttp/4.10.0
https://i.mjh.nz/10-nsw.m3u8
```

Thanks Matt

**Comment by matthuisman** [comment]
Every app is different so I'm not sure sorry. If that app supports Kodi
style, then the Kodi playlist should work as that adds the user agent
header . Otherwise you'll need google how to set it in the app you use

**Comment by matthuisman** [comment]
oh, your also using old links.
The urls are https://i.mjh.nz/.r/10-nsw.m3u8
(thats probably your issue)

`https://i.mjh.nz/.r/10-nsw.m3u8|user-agent=Mozilla/5.0%20%28Windows%20NT%2010.0%3B%20Win64%3B%20x64%29%20AppleWebKit/537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome/98.0.4758.102%20Safari/537.36`

**Comment by tehfonz** [comment]
If I run this command:
`. 'C:\Program Files\NextPVR\Other\ffmpeg.exe' -i https://i.mjh.nz/.r/channel-9-nsw.m3u8`
I get an output, it appears to work (it starts trying to stream the video in the Powershell window)

If I run this command:
`. 'C:\Program Files\NextPVR\Other\ffmpeg.exe' -i https://i.mjh.nz/.r/10-nsw.m3u8`
It returns: 
```
Trailing option(s) found in the command: may be ignored.
[https @ 02d5adc0] HTTP error 404 Not Found
https://i.mjh.nz/.r/10-nsw.m3u8: Server returned 404 Not Found
```

does that point to anything?
I have checked my firewall and allowed all from the server running this command.

**Comment by matthuisman** [comment]
https://i.mjh.nz/.r/10-nsw.m3u8 redirects to 
https://dai.google.com/ssai/event/kIanX1fxR7isFhfnvLSKTA/master.m3u8 which redirects to 
https://dai-ads-delivery.10play.com.au/MjAyMA5AV1f-20211022/10NSW-b.m3u8?v=gam&originpath=/linear/hls/pb/event/kIanX1fxR7isFhfnvLSKTA/stream/8d9c9162-5e2c-41b4-963c-d892c0d033c7:TPE/master.m3u8 
which finally redirects to 
https://dai.google.com/linear/hls/pb/event/kIanX1fxR7isFhfnvLSKTA/stream/8d9c9162-5e2c-41b4-963c-d892c0d033c7:TPE/master.m3u8

**Comment by tehfonz** [comment]
I can now get a little further, but still cannot stream and now can get this error with ffmpeg:

```
[hls @ 0350a480] Opening 'https://net10-livestream-keys.play.cbsi.video/10NSW/key/K151000.key' for reading
[https @ 03525d80] HTTP error 404 Not Found
[hls @ 0350a480] Unable to open key file https://net10-livestream-keys.play.cbsi.video/10NSW/key/K151000.key
[hls @ 0350a480] Opening 'crypto+https://net10-livestream.play.cbsi.video/10NSW/stream120241101T052944_151094.ts' for reading
[hls @ 0350a480] Error when loading first segment 'https://net10-livestream.play.cbsi.video/10NSW/stream120241101T052820_151080.ts'
https://dai.google.com/linear/hls/pb/event/kIanX1fxR7isFhfnvLSKTA/stream/134fa0a4-991a-4e55-804b-fb9c84a3aed4:TPE2/master.m3u8?authuser=0: Invalid data found when processing input
```

**Comment by tehfonz** [comment]
Ah, I got it working in VLC using this user-agent code:
:http-user-agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36'
Now how to translate that to NextPVR :|

**Comment by sbiddle** [comment]
> Ah, I got it working in VLC using this user-agent code: :http-user-agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36' Now how to translate that to NextPVR :|



Very simple. You've overcomplicated things by trying to use ffmpeg. You simply need this in your m3u8 file for IPTV channels

#EXTINF:-1 tvg-ID="10 HD Melbourne" tvg-chno="908" tvg-logo="https://i.mjh.nz/.images/tv.101406020625.png" group-title="Australia",10
#EXTVLCOPT:http-user-agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36'
https://i.mjh.nz/.r/10-vic.m3u8
