### ISSUE TITLE
json m3u8 ?

### ISSUE THREAD

**Issue by openn1** [matthuisman/i.mjh.nz#148]
friend, did you removed all m3u8 on .app.json ??

**Comment by matthuisman** [comment]
See pinned issue

**Comment by openn1** [comment]
Absolutly Bullshit the copyright issue cant be never on the samsung they have license for make it public. So On samsung cant never the case.

**Comment by matthuisman** [comment]
they didnt dmca those. Read through that issue, people have provided urls that will generate playlists from the json files

**Comment by openn1** [comment]
So you have now delete the json ? or its comming back?

**Comment by openn1** [comment]
hello, why did you remove the .json  ?  is that you are:
* Disapointed
* Angry
*  Im not say Happy Birthday?
* Becourse your country is soon be flooded with water ? 
* you are living upside down ?
Of what ? Please put at least the .json back for the correct epg.
