### ISSUE TITLE
How can i use these

### ISSUE THREAD

**Issue by Tronus1409** [matthuisman/i.mjh.nz#149]
Title says it all, how do i add these to jellyfin

**Comment by matthuisman** [comment]
Not sure sorry. I don't use jelly fin. Best to ask on their forums

**Comment by crmorton** [comment]
I got @matthuisman's [Australia IPTV & EPG Files](https://www.matthuisman.nz/2017/07/australia-iptv-epg-files.html) to work in JellyFin. You need to do three things:
1. Add an **M3U Tuner** as a **Tuner Device** in JellyFin
2. Add an **XMLTV** EPG as a **TV Guide Data Provider** in JellyFin
3. (Optional) Set **User agent** to `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36&seekable=0&referer= ` in the **Tuner Device** and **TV Guide Data Provider**

Here's a screenshot of what it looks like in JellyFin from the [**Administration Dashboard**](http://localhost:8096/web/index.html#/dashboard):

![image](https://github.com/user-attachments/assets/1303e366-8e4d-46e2-8c62-154ce8724886)

Detailed Instructions and Screenshots are:
1. Add `https://i.mjh.nz/au/{REGION}/raw-tv.m3u8` url as a **Tuner Device**, by selecting **M3U Tuner** as the **Tuner type**

   ![image](https://github.com/user-attachments/assets/4605e5e0-242a-4da3-b215-caf942aa9f98)
 
2. Add `https://i.mjh.nz/au/{REGION}/epg.xml.gz` url as an `XMLTV` **TV Guide Data Providers**

   ![image](https://github.com/user-attachments/assets/ae56e847-811a-49eb-b4ab-df8e90419584)

3. For my `{REGION}` (Canberra), I used the following Category Selector(s):

   | Programme Category    | Category Selector(s)                                                                                                                                                                                                                                                                                                                               |
   |-----------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
   | Movie categories      | Movies\|ACTION MOVIE\|Action Movie\|THRILLER MOVIE\|Animation Movie                                                                                                                                                                                                                                                                                |
   | Children's categories | Kids\|Kids and Family\|Children & Family\|Family                                                                                                                                                                                                                                                                                                   |
   | News categories       | News\|Documentary\|News And Factual\|News, Current Affairs\|News Magazine\|Social, Political Issues, Economics\|Social, Political Issues, Economics (general)\|Discussion, Interview, Debate\|News and Information\|Education, Science, Factual Topics (general)\|OTHER DOCUMENTARY SERIES\|DOCUMENTARY SERIES\|NEWS\|SOCIETY DOCUMENTARY\|Factual |
   | Sports categories     | Sports\|Sport\|MOTORCAR SPORT\|CRICKET\|GOLF\|FIELD HOCKEY\|SPORT\|BOXING\|SPORTS OTHER\|                                                                                                                                                                                                                                                          |
