### ISSUE TITLE
Pluto TV Norway, Sweden and Denmark

### ISSUE THREAD

**Issue by CHJ85** [matthuisman/i.mjh.nz#15]
Hi there.
Could you please add the new Pluto TV channels for Norway, Sweden and Denmark?
Thanks for all your work.

**Comment by matthuisman** [comment]
done :)

**Comment by CHJ85** [comment]
Thank you! 😀

**Comment by CHJ85** [comment]
Btw. Austria and Switzerland.
That should cover the entire Pluto TV market, for now anyway.
They're constantly expending to new countries.

**Comment by matthuisman** [comment]
as far as i can tell they both use same as germany

**Comment by CHJ85** [comment]
Not really. Same language though (German). But I did take a look at Pluto.tv using different VPN locations and they do have a slightly different channel selection.

**Comment by matthuisman** [comment]
ok, i have added them.
Can you check and see if they look correct?
to me they look the same, but happy to keep if they actually do have different content

**Comment by CHJ85** [comment]
Yea, I'm sorry. They seem to all have the same channels.
I guess the only difference is the advertisements.

**Comment by matthuisman** [comment]
right, should I keep or not?
I'll let you decide haha

**Comment by CHJ85** [comment]
Idk. If I was from Austria or Switzerland, I'd prefer ads from my own country. And I guess that's fair considering that's how Pluto TV makes their money.
So you might as well keep em now that they've been added.
