### ISSUE TITLE
Pluto TV EPG broken

### ISSUE THREAD

**Issue by matthuisman** [matthuisman/i.mjh.nz#16]
should be able to look at this today

**Comment by geonsey** [comment]
I did not realize you were here. I have it bookmarked for future reference. Thanks for your attention. -GB

**Comment by matthuisman** [comment]
Haha. I'm everywhere!

**Comment by matthuisman** [comment]
ok, the problem was that I was scraping Canada that suddenly started returning 0 channels causing script to exit as it expected at least 10

[url_alt](https://www.thestar.com/business/2022/06/08/ad-supported-streaming-platform-pluto-tv-coming-to-canada-in-deal-with-corus.html)
Looks like its not even there yet - so not sure what it has been scraping until now.

So have removed Canada.
Also removed Austria and Switzerland as same as Germany

**Comment by geonsey** [comment]
Looks like you fixed it! Thank you for your dedicated work, my friend! -GB

**Comment by geonsey** [comment]
> ok, the problem was that I was scraping Canada that suddenly started returning 0 channels causing script to exit as it expected at least 10
> 
> [url_alt](https://www.thestar.com/business/2022/06/08/ad-supported-streaming-platform-pluto-tv-coming-to-canada-in-deal-with-corus.html) Looks like its not even there yet - so not sure what it has been scraping until now.
> 
> So have removed Canada. Also removed Austria and Switzerland as same as Germany

I am in Canada, so although the Pluto TV list is very small (for now-- it's expanding FINALLY this autumn), the entire CA list populated EPG just fine... (just feedback for you)
