### ISSUE TITLE
[Request] M3U8 list & epg for MX region of SamsungTVPlus

### ISSUE THREAD

**Issue by Mikhel** [matthuisman/i.mjh.nz#17]
Hi, this is not really an issue but a mere request to check whether you could get the m3u8 and epg for mexico's for SamsungTV Plus(I think it is MX region).

Thanks in advance.

**Comment by matthuisman** [comment]
Can't help sorry. I only get which are available via the android app not tv
app

**Comment by Mikhel** [comment]
Thanks, didn't know that source :)
