### ISSUE TITLE
Open shop,  ACCTV and 3AW Melbourne not working 

### ISSUE THREAD

**Issue by Cloudman999** [matthuisman/i.mjh.nz#21]
Hi @matthuisman 
Could you please advise if the openshop,  ACCTV and 3AW Melbourne channels are working? 

Playlist: https://i.mjh.nz/au/Melbourne/kodi-tv.m3u8

System: Android mobile

Player:Televizo

No log file,  sorry

PS all other channels in the above playlist work. 

Regards
@Cloudman999

**Comment by matthuisman** [comment]
openshop gone:
https://tvtonight.com.au/2021/08/openshop-channel-in-administration.html
(ill remove)

**Comment by Cloudman999** [comment]
Hi @matthuisman 
Thank you for advising openshop is no more.
Also appreciate you fixing ACCTV and 3AW.

Best regards
@Cloudman999
