### ISSUE TITLE
Without internet

### ISSUE THREAD

**Issue by Mobi0007** [matthuisman/i.mjh.nz#23]
Hello matt.i have currently got imerge on my Android and it is a terrific setup.I was wondering is there a way to use imerge and not use internet.Some how get it to default to standard arial.It makes no sense to use internet when I have very good picture.i just don't want to be flicking from hdmi to DTV all the time if there is an easy solution.Any ideas?

**Comment by matthuisman** [comment]
The I in IPTV stands for internet. Aerial / terristerial tv is completely different. In conclusion, the answer is no
