### ISSUE TITLE
Stirr logos are broken

### ISSUE THREAD

**Issue by Mikhel** [matthuisman/i.mjh.nz#24]
Hi, as of recently I have noticed that the majority of logos from Stirr do not display, is it an issue with the provider that changed them or a different issue?

Saludos.

**Comment by matthuisman** [comment]
all working for me, make sure your running latest 19.2.2 IPTV Simple Client

**Comment by Mikhel** [comment]
Thanks I just checked it again on my PC and noticed that access to the logos is restricted from my area.

**Comment by matthuisman** [comment]
Oh, maybe I could save them all to my server and serve them from their

**Comment by Mikhel** [comment]
Oh that would be neat, thanks in advance :)
