### ISSUE TITLE
Channel logo link issue Stirr

### ISSUE THREAD

**Issue by evilash3** [matthuisman/i.mjh.nz#25]
Howdy, 
I have noticed that for roughly a month or so the channel logo images for Stirr on your site seem to be broken links.

Just thought I would bring it to your attention.

**Comment by matthuisman** [comment]
thanks for letting me know. looks like they moved the image location again. ill investigate :)

**Comment by matthuisman** [comment]
oh, they geo-blocked the image urls - haha. Never seen that before.
So, i'm now downloading the images and storing on my server and linking to those - so should be now fixed :)

**Comment by evilash3** [comment]
Funny the stuff they come up with.
Thanks for sorting this out.
Keep up the good work.
