### ISSUE TITLE
Missing Plus1 channel EPG info from NZ freeview.

### ISSUE THREAD

**Issue by ashleyw-gh** [matthuisman/i.mjh.nz#27]
I notice in the EPG for NZ Freeview that the EPG for the "plus 1 channels" all seems to be missing.. Is this information no longer available? (seems to have started happening in last few weeks). Or would I need to parse the normal EPG info from your xml file then rewrite the plus1 channels EPG with a different time offset?

**Comment by matthuisman** [comment]
I recently re-wrote the generator code to just output epg for the playlist entries. as there are no entries for +1's, they don't get outputted. I totally forgot about users using tuners that may very well have a need for the EPG. I'll get them added back in today sometime

**Comment by matthuisman** [comment]
they should now be back :)

**Comment by ashleyw-gh** [comment]
awesome, I've run an import. I don't see the EPG info for ThreePlus1 or eden+1 in the xml file. 

I do see the others but the EPG for those doen't seem to be coming through to tvheadend though despite the mappings etc being correct (could be a caching issue on my side - so will investigate further)

**Comment by matthuisman** [comment]
Oh sorry, I forgot those had +1s now as well. Will fix shortly. 😂

**Comment by matthuisman** [comment]
fixed now

**Comment by ashleyw-gh** [comment]
thank-you. nice work! All working perfectly again now! Guide looks complete again!
If you could just fix the lack of anything worth watching though, that would be great!

**Comment by eroyee** [comment]
Hi, 

Sorry to raise this thread from the dead, but it appears the +1 data has dropped again? 

Was this by intent, or is there a chance it'll appear again at some point?

Thanks.

**Comment by matthuisman** [comment]
oops sorry. should come back in the next scrape (within next hour)

**Comment by eroyee** [comment]
Cheers 👍
