### ISSUE TITLE
Issue with Pluto EPG , making kodi crash

### ISSUE THREAD

**Issue by Time-Pare** [matthuisman/i.mjh.nz#29]
Hi, sorry english isn't my language.
I'm on Kodi and i have IPTV Merge, i have mutiple playlist and epg from you and iptv org.  
Every 2 months the pluto playlist make my kodi crash on all my device without crash log and i can't relaunch kodi until y remove the epg file in the roaming folder. I removed all epg and playlist and add them back one to one and merge untill it start crashing again and i found it was when i add the Pluto all.xml file. Can you help me figuring out how to not make it crash again?

Thanks, have a nice day.

Edit : sorry my mistake, it's the Plex playlist, not the pluto one.

**Comment by matthuisman** [comment]
see here: https://forum.kodi.tv/showthread.php?tid=340691&pid=3121929#pid3121929
I suspect its IPTV Simple issue
