### ISSUE TITLE
Quality Select

### ISSUE THREAD

**Issue by kingy444** [matthuisman/i.mjh.nz#3]
Hey Matt - I can see the new feature here for your addons https://www.matthuisman.nz/2019/09/new-quality-select-in-my-add-ons.html

is there any attribute we can add to the rtsp stream to force a certain quality?

Running the rtsp stream in VLC works fine , with small to start increasing to match your quality once loaded

Adding these to emby results in emby analysing the initial stream size and never providing full quality. Obviously an issue on EMBY side, but probably easier if can request quality via a direct rtsp stream aswell ?

**Comment by matthuisman** [comment]
what add-on of mine does this affect???

**Comment by kingy444** [comment]
so no way to request the stream to start high quality and not at 480p to start with?

**Comment by matthuisman** [comment]
in kodi?

**Comment by kingy444** [comment]
just using the rtsp streams directly - thats why i asked specifically on this repo

**Comment by matthuisman** [comment]
Quality select = Kodi only feature
You'll need to ask whoever makes the player your using
