### ISSUE TITLE
Ffmpeg discontinuity tvheadend

### ISSUE THREAD

**Issue by liam8888999** [matthuisman/i.mjh.nz#31]
Do you know of a version of ffmpeg with a discontinuity patch for recording from your Australian tv m3u8 on tvheadend. It loses picture at add breaks however the audio continues but the image never comes back. Exactly the same as what happens with binge live channels in kodi if that helps to explain

**Comment by matthuisman** [comment]
There is a ffmpeg patch floating around for years. You'll need to apply it yourself and build
