### ISSUE TITLE
Adding any SlyGuy AddOns knocks out the channels that were already there

### ISSUE THREAD

**Issue by npmstart-pray** [matthuisman/i.mjh.nz#35]
I had the Canadian Broadcast Corporation Addon working in my kodi (IP)TV.
Then I added SlyGuy to grab (the now-launched in Canada) PlutoTV, and with crossed fingers, the PBS station that broadcasts to the Toronto Market. (I'm hoping there's a little wiggle room on the US IP addy requirement - America is literally 6 miles to the right of me as I type, and their broadcast transmitter reaches -and they market to- Toronto, the largest Canadian Market)
Gone are the CBC channels that IPTV Manager had nicely set up so that I could avoid opening the CBC addon.  They're still available if I do use it rather than accessing them through the guide, but the kablammo! disappearance of what WAS working is a little disconcerting.  
Do IPTV Manager and IPTV Merge not play nicely together, I wonder? Is it an IPTV Simple misconfiguration?  Surely there must be a method to get everything to co-exist...might it have something to do with m3u or EPGs? How do I grab one or the other and insert it where it'll work on my kodi?

**Comment by matthuisman** [comment]
just use IPTV Merge. It supports any addons that support IPTV Manager.

**Comment by npmstart-pray** [comment]
I'll give it a shot, thanks.
Happy Holidays!  I see you pushed an update to IPTV Merge...

**Comment by matthuisman** [comment]
Update was unrelated to this. I added support for IPTV manager add-ons
quite some time ago as it's annoying to need to use two different addons

**Comment by npmstart-pray** [comment]
Happy New Year. Getting rid of IPTV manager helped immensely. Still can’t get the PBS station I’d like, but that’s something I’ll dig deeper into when I’ve another few moments. Thank you!Sent from nowhere near my ready room with my new tricorderOn Dec 23, 2022, at 16:11, Matt Huisman ***@***.***> wrote:﻿
Update was unrelated to this. I added support for IPTV manager add-ons
quite some time ago as it's annoying to need to use two different addons
