### ISSUE TITLE
Samsung: Show Titles contain both Show and Episode name

### ISSUE THREAD

**Issue by bgiesing** [matthuisman/i.mjh.nz#36]
I use Channels DVR with the US M3U/XML links and many channels put the show title and episode name together as the show title making for a new show entry for every single episode cluttering my library, any chance you can have your parser split the data?

For example, the Modern Marvels channel has guide entries named like "Modern Marvels: Beans" when it should be show "Modern Marvels" and episode "Beans". Some other channels instead use a dash as the separator like Dance Moms "Dance Moms - A Team On Trial".

**Comment by matthuisman** [comment]
What about shows that have : or - in their actual name?

**Comment by bgiesing** [comment]
The only thing I can think of is check the channel name as a comparision? Wouldn't cover every single instance but would prevent false positives. 

Like if you see  a show on a channel called "Modern Marvels" is called "Modern Marvels: Beans" it's a pretty safe assumption that it should actually be "Beans"

**Comment by matthuisman** [comment]
did a few tweaks. try the latest epg

**Comment by bgiesing** [comment]
Yep that seems to have fixed it in a lot of cases, still shows up occasionally on some channels that aren't just 24/7 of the same show (like #1233 Deal Zone) but it's likely the best that can be done unless Samsung provides better source data
![image](https://user-images.githubusercontent.com/7895463/212830835-1cd3de84-86a8-4a29-a139-6487e52fb2d1.png)
