### ISSUE TITLE
QVC+|HSN+ support?

### ISSUE THREAD

**Issue by bgiesing** [matthuisman/i.mjh.nz#37]
Most of these sources already have QVC and HSN proper but not the online exclusive spinoff channels like Plus Originals, In The Kitchen, and Fashion Finds available on https://plus.qvc.com.

The EPG guide is here https://plus.qvc.com/program-guide to scrape, shows 7 days worth ahead

**Comment by matthuisman** [comment]
not for me sorry. you could try ask here: https://forums.whirlpool.net.au/thread/9nk6qzy3
