### ISSUE TITLE
ABC News/Weather/Business in 90 seconds

### ISSUE THREAD

**Issue by Ozman** [matthuisman/i.mjh.nz#39]
Hi Matt, these channels have not updated in a couple of weeks or more. Running VIM3L using CoreElec with Kodi up-to-date. I have run IPTV merge several times but the problem remains.

**Comment by matthuisman** [comment]
Thanks for opening an issue. I had forgot about this.

**Comment by matthuisman** [comment]
should be fixed now

**Comment by Ozman** [comment]
Sorry to trouble you Matt but the ABC News/Weather/Business in 90 seconds has stopped working again. Does the ABC keep fiddling with it?
