### ISSUE TITLE
enhancement request for plex epg

### ISSUE THREAD

**Issue by yarafie** [matthuisman/i.mjh.nz#4]
Hello,

First would like to really thank you for the work you've done in generating these m3u and epg.

I noticed in the Plex US epg some of the program titles are awkward. Example is popcornflix epg.

Titles of program shows Episode 1 or  Pilot Part 1 which does not reflect the actual show.

Snapshot attached. 

![Screenshot_20211130-074506_LazyIptv Deluxe](https://user-images.githubusercontent.com/88841013/143987583-e7a54c52-5486-4104-bd84-4160ef5555b7.png)

> I just provide the same as Plex does so not sure what can be done here sorry

Ok. Reason I ask is that I actually have Plex live TV in Plex and in their guide it shows the correct title.

**Comment by matthuisman** [comment]
I just provide the same as Plex does so not sure what can be done here sorry

**Comment by yarafie** [comment]
Will Do

**Comment by yarafie** [comment]
Ok did a quick compare see attached snapshots see 2:00am for popcornflix shows Flash Gordan S1 E1 in the Plex guide in yours its shows Pilot Part 1. I attached second snapshot showing full details of 
![Screenshot_20211130-080706_Plex](https://user-images.githubusercontent.com/88841013/143989127-d94ac4f6-31e1-45ce-aae3-aa647ff0c3db.png)
![Screenshot_20211130-080459_Plex](https://user-images.githubusercontent.com/88841013/143989137-8b5a66fd-b8f6-460b-8e28-12801c14fcb1.png)
show

**Comment by yarafie** [comment]
It appears you are not grabbing all the title just the third line which is Pilot Part 1 and not the 2 earlier lines :) hope that helps

**Comment by yarafie** [comment]
Thanks  again

**Comment by yarafie** [comment]
Spiders web full info for comparison 
![Uploading Screenshot_20211130-081310_Plex.png…]()

**Comment by yarafie** [comment]
![Screenshot_20211130-081930_Plex](https://user-images.githubusercontent.com/88841013/143990017-24520ba3-c958-48c0-bde5-90da8fd69672.png)

**Comment by yarafie** [comment]
You can also check today's at 2pm and 3pm same thing
![Screenshot_20211130-082518_Plex](https://user-images.githubusercontent.com/88841013/143990584-e99f4ea1-e09a-4aab-bfb4-5b4620b9d90c.png)
![Screenshot_20211130-082733_Plex](https://user-images.githubusercontent.com/88841013/143990697-cb024b10-53b6-47ec-8e56-9214f7460089.png)
![Screenshot_20211130-082747_Plex](https://user-images.githubusercontent.com/88841013/143990706-5b529677-1b59-40d9-b0c1-b0f3831db256.png)


popcornflix

**Comment by matthuisman** [comment]
I'll take a look. I can't pull any info that their api doesn't present in the main initial call. I can't request info for every individual show. So as long as the show name is available in the main request, should be doable. Plex have very strict api limits and it's very nearly to the point of stopping the EPG. As cbf with it

**Comment by matthuisman** [comment]
ok, try latest epg - should be a bit better

eg

```
  <programme channel="5e20b730f2f8d5003d739db7-60089d8df682a3002c348297" start="20211201120150 +1300" stop="20211201130234 +1300">
    <title>Flash Gordon</title>
    <sub-title>Pilot Part 1</sub-title>
    <episode-num system="onscreen">S01E01</episode-num>
    <desc>Part 1: Flash Gordon thought  his father died in a fire 13 years ago when actually, he disappeared through a "rift", traveling to the planet Mongo. Flash is forced to team up with his ex-girlfriend, Dale Arden, who travels with him to Mongo to meet Ming, the planet's brutal dictator.</desc>
    <date>20211123</date>
    <icon src="https://images-us-am.crackle.com/1/i/em/2y1yb_tnl_1920x1080.jpg?ts=20210823183512"/>
  </programme>
```

**Comment by yarafie** [comment]
You are the man 👨 👍👍
