### ISSUE TITLE
Samsung TV Plus

### ISSUE THREAD

**Issue by surfin55** [matthuisman/i.mjh.nz#45]
Hi Matt,
Are we able to see the Australian content using your app?
I understand that there will be new content starting this Thursday from Sky News Australia (IPTV channel "Sky News Now")
This was from an article in the Australian newspaper today 20/03/2023 "Sky unveils a new digital platform"
Thanks
Peter Morrison

**Comment by matthuisman** [comment]
no. I use the android mobile app for scraping and that doesnt yet work in Australia

You could use [https://www.apsattv.com/ssungaus.m3u](https://forums.whirlpool.net.au/go?https%3A%2F%2Fwww.apsattv.com%2Fssungaus.m3u)

**Comment by matthuisman** [comment]
as per here:https://forums.whirlpool.net.au/thread/9nk6qzy3
