### ISSUE TITLE
ABC News/Weather/Business in 90 seconds has stopped working again

### ISSUE THREAD

**Issue by Ozman** [matthuisman/i.mjh.nz#46]
Sorry to trouble you Matt but the ABC News/Weather/Business in 90 seconds has stopped working again. Does the ABC keep fiddling with it?

_Originally posted by @Ozman in https://github.com/matthuisman/i.mjh.nz/issues/39#issuecomment-1499671662_

**Comment by Ozman** [comment]
Sorry to trouble you Matt but the ABC News/Weather/Business in 90 seconds has stopped working again. Does the ABC keep fiddling with it?

**Comment by matthuisman** [comment]
fixed now. 
yes, the video urls for the channels is embedded in a html webpage (https://www.abc.net.au/news/newschannel/news-in-90-seconds)  so i need to scrape that to pull them out and they keep changing it :)
