### ISSUE TITLE
Flash News App Kodi

### ISSUE THREAD

**Issue by surfin55** [matthuisman/i.mjh.nz#49]
Flash App version 0.0.8 on Kodi windows 11
I have been receiving this error executing it from the live tv guide, for the last couple of days, is anybody else experiencing the same error.

![Flash 1](https://github.com/matthuisman/i.mjh.nz/assets/42806795/610612e9-3c0a-46df-8913-0928367317ad)

**Comment by matthuisman** [comment]
fixed in [slyguy.flashnews -> v0.0.9](https://github.com/matthuisman/slyguy.addons/commit/3b983080a2409fbbab57abbe6a23e5c31bf0c643)
