### ISSUE TITLE
error in epg url for Stirr M3U

### ISSUE THREAD

**Issue by infojoe** [matthuisman/i.mjh.nz#52]
The egp for Stirr in the m3u file is:
#EXTM3U x-tvg-url="https://i.mjh.nz/Stirr/epg.xml.gz"

it should be:
#EXTM3U x-tvg-url="https://i.mjh.nz/Stirr/all.xml.gz"

or just rename "all.xml.gz" to "epg.xml.gz"

**Comment by matthuisman** [comment]
good find! fixed now in code. playlist will be fixed next time it generates
