### ISSUE TITLE
TVNZ Streams Down

### ISSUE THREAD

**Issue by sanjay900** [matthuisman/i.mjh.nz#54]
I can't seem to play anything from https://i.mjh.nz/nz/kodi-tv.m3u8, and when i try going to one of the channels, say channel one, it takes me to a cloudfront.net url that just 404s
for example, https://d2ce82tpc3p734.cloudfront.net/v1/master/b1f4432f8f95be9e629d97baabfed15b8cacd1f8/TVNZ_1/master.m3u8

Has this potentially been hit by the new changes to tvnz streaming?

**Comment by matthuisman** [comment]
Think the urls have changed. Hopefully to better quality ones. I'll try fix
tonight

**Comment by sanjay900** [comment]
thank you

**Comment by matthuisman** [comment]
Looks like TVNZ has gone to WV DRM dash live streams.

Therefore, once I make changes to support it - only Kodi addon and some android IPTV apps will support the TVNZ channels

**Comment by sanjay900** [comment]
Interesting. That will be okay for me since i am using kodi, but hopefully that doesn't affect too many people.

**Comment by charlieglue** [comment]
if fks any1 using PVR software to have all there channels in once place i doubt many if any would be able to pay the $$$ for the DRM certs

**Comment by matthuisman** [comment]
fixed now. no DRM needed yet

**Comment by charlieglue** [comment]
nice lets hope it stays this way

**Comment by matthuisman** [comment]
ive got the DRM streams "ready to go" if needed :)

**Comment by paul19920801** [comment]
Are you able to provide the DRM protected streams? I'm going to look into the feasibility of stripping the DRM protection the streams can still be used with Kodi.

**Comment by matthuisman** [comment]
Kodi can play the DRM streams fine.
My tvnz Kodi addon uses the DRM streams I believe
