### ISSUE TITLE
Do EPG / Playlist for Roku Channel (now that it has an android tv app)

### ISSUE THREAD

**Issue by matthuisman** [matthuisman/i.mjh.nz#58]

**Comment by DeltaSr95** [comment]
Any luck?

**Comment by matthuisman** [comment]
All data now scraped. just need to generate playlists etc

example epg:
![image](https://github.com/matthuisman/i.mjh.nz/assets/6225961/2511fd38-c3eb-40bc-a838-2566c9fd2e31)

HLS Channels:  170  (work on most players)
Widevine channels:  284  (only work in kodi and some android iptv players)
It appears the HLS are not geo-locked but the widevine ones are.

**Comment by HDGuy** [comment]
Access to the on demand content as well or just the "livestream" stuff?

**Comment by matthuisman** [comment]
closing this due to https://github.com/matthuisman/i.mjh.nz/issues/127
