### ISSUE TITLE
channels from Brazil

### ISSUE THREAD

**Issue by kuesttman** [matthuisman/i.mjh.nz#60]
Is it possible to add channels from Brazil to SamsungTVPlus? There are more than 100 channels from Brazil for SamsungTVPlus that are not in the updated list in the repository.
PlutoTV has "br.xml" with Brazilian content, but SamsungTVPlus does not.

It would be interesting if other legal IPTV services had content and channels from Brazil in Portuguese.

**Comment by matthuisman** [comment]
I automate the playlists using the Samsung tv plus android app which is only available in some regions. Brazil is not one of those

However, another kiwi hosts a manually created Samsung tv plus Brazil playlist here
https://www.apsattv.com/streams.html
