### ISSUE TITLE
Add Sky Open stream

### ISSUE THREAD

**Issue by matthuisman** [matthuisman/i.mjh.nz#61]
Has replaced Prime

https://www.sky.co.nz/skyopen/howtowatch
https://freeviewnz.tv/channel/28
https://www.sky.co.nz/skyopen#:~:text=Q.%20What's%20happened%20to%20Prime,programmes%20available%20on%20the%20channel.

**Comment by vaughanreed** [comment]
Thanks Matt. SkyTV mentioned that the feed should be the same as Prime, but when I run the Prime feed (https://i.mjh.nz/prime.m3u8), it just times out. With the World Cup Rugby starting soon, the Sky Open feed is going to be popular :-)

**Comment by matthuisman** [comment]
ill get it updated tonight

RIP PRIME

**Comment by matthuisman** [comment]
hmm. the current urls are working for me....

Maybe there was just a down period while they switched?

**Comment by matthuisman** [comment]
ill update the channel name and logo though

**Comment by matthuisman** [comment]
done
