### ISSUE TITLE
Channel 7 Australia Regional Feeds

### ISSUE THREAD

**Issue by CrazyErrorGamer** [matthuisman/i.mjh.nz#62]
This isn't really an issue, more like a suggestion.

I know that on 7Plus that you can watch some regional feeds of the main Channel 7 station, such as 7 Gold Coast, 7 Sunshine Coast, 7 Cairns etc. depending on your location. As far as I know, the Seven Network is the only network that provides regional feeds via its on-demand service.

I'm just wondering if it would be possible for you to integrate these regional feeds into the Australia playlist in some way.

The benefit of regional feeds is having local news bulletins and advertising, and potentially special region-only events being broadcasted but that is about it really.

I don't really mind if this doesn't get added, seeing as it isn't essential and all, but it would be a nice thing to have for those who are in these regional areas and would like to use IPTV without missing out on their local news bulletin.

**Comment by matthuisman** [comment]
The 7 plus kodi addon allows setting your lat/long. Can you use that to get access to the feeds via the addon?

**Comment by CrazyErrorGamer** [comment]
I'll try it out tomorrow night on 7 Gold Coast when the local Gold Coast news comes on at 5:30pm.

**Comment by matthuisman** [comment]
how did you go?

**Comment by CrazyErrorGamer** [comment]
Wasn't able to check due to not being at home, will check next Monday (since local news is only on weekdays).

**Comment by CrazyErrorGamer** [comment]
> how did you go?

It works! I was able to watch the local news bulletin.
