### ISSUE TITLE
TVheadend version of Pluto TV m3u

### ISSUE THREAD

**Issue by Sydneybrit** [matthuisman/i.mjh.nz#63]
Could we get a version of the Pluto TV m3u that has Pipe/FFmpeg commands embedded in a similar way to https://i.mjh.nz/au/Sydney/tvh-tv.m3u8

**Comment by matthuisman** [comment]
DONE :) 
https://i.mjh.nz/PlutoTV/

now there is -kodi and -tvh versions of each :)
