### ISSUE TITLE
Plex es.m3u8 list?

### ISSUE THREAD

**Issue by wuniversales** [matthuisman/i.mjh.nz#65]
I am surprised that there is no plex list in Spanish.
en.m3u8
nor the xml guide...

**Comment by matthuisman** [comment]
what country? Spain or Mexico?

**Comment by matthuisman** [comment]
i have just added Mexico Plex playlists to https://i.mjh.nz/Plex/

**Comment by wuniversales** [comment]
Spain xD

**Comment by matthuisman** [comment]
removed Mexico and added spain

**Comment by Mikhel** [comment]
could you keep Mexico? In Mexico i can only access a few plex channels from m3u lists but with the mex lising you added i could access every one intended for my region.

Thanks in advance.

**Comment by matthuisman** [comment]
done :)

**Comment by Mikhel** [comment]
Thanks a lot, much appreciated.

Saludos.
