### ISSUE TITLE
IFood.tv from Roku

### ISSUE THREAD

**Issue by boeder9** [matthuisman/i.mjh.nz#70]
Hey mjh,

First off, I can't thank you enough for the impeccable work you do, just amazing man!

Also big thank you for Roku, I wanted to ask if iFood.tv can be added to Roku, it should be on there.

Once again, thank you so much, you rock!

God bless

**Comment by matthuisman** [comment]
https://i.mjh.nz/Roku/all-kodi.m3u8 is it o
In there?

Most of there channels have widevine drm so don't get put on the other playlist types

**Comment by matthuisman** [comment]
you sure its part of there "normal" channels? and not an extra roku app?

I scrape "The roku channel' android app
[com.roku.web.trc](https://play.google.com/store/apps/details?id=com.roku.web.trc)

**Comment by boeder9** [comment]
I'm actually not sure, I don't have Roku but it was a channel on there, it was on Rakuten too but recently removed (stream still works though – no epg).

If you scrapped the entire playlist, it's fine, I don't want to waste more of your time.

I am using the "all.m3u8" playlist on Tivimate, I noticed it has less channels than the Kodi variant, so now I know why.
