### ISSUE TITLE
Channel 7 streams not working

### ISSUE THREAD

**Issue by Smark223** [matthuisman/i.mjh.nz#73]
All Channel 7 streams including 7mate, 7flix, 7mate don't seem to be working

eg. https://i.mjh.nz/seven-mel.m3u8

Don't think this is a DNS proxy/VPN issue for me as Channel 9, SBS, ABC etc work fine.

**Comment by matthuisman** [comment]
Try on 7 website. "Others working" means nothing

**Comment by Smark223** [comment]
They aren't working on the website either. With an Australian VPN, it says "We are experiencing a technical issue with 7plus" and I get an error code MEDIA_ERR_DECODE. Using SmartDNS, the streams just don't load. Both previously worked, so I guess 7 have made some changes

**Comment by matthuisman** [comment]
yes. they may have tightened things up. Maybe let SmartDNS know. they may be able to swap to a different IP
please try website / official apps in future first as that tells you if its a blocking or invalid url

**Comment by Smark223** [comment]
Sure, will do. Apologies, I should have done that first.
