### ISSUE TITLE
New Channels for IPTV AU m3u8

### ISSUE THREAD

**Issue by mjk1984** [matthuisman/i.mjh.nz#75]
Any chance the following can be added to the IPTV m3u8 file for Australia

- Bloomberg 4k (stream is freely available on Samsung TV)
- Sky News Australia (stream is freely available on Samsung TV)
- SBS Chill channel (available on the SBS App as a TV Channel, on top as a DAB radio channel)

**Comment by matthuisman** [comment]
Sky News Australia: is that the same as Sky News Now?
I cant see any others in https://www.apsattv.com/ssungaus.m3u

bloomberg is there i believe:
https://bloomberg-bloomberg-2-au.samsung.wurl.tv/playlist.m3u8

**Comment by matthuisman** [comment]
any reason you cant use https://www.apsattv.com/ssungaus.m3u to get Bloomberg and Sky news?

**Comment by matthuisman** [comment]
SBS Chill added

**Comment by matthuisman** [comment]
Bloomberg 4k (but actually 1080p) added

**Comment by matthuisman** [comment]
added sky news now as well.

SBS chill and sky news now both have no epg
