### ISSUE TITLE
Channel 1000 on Melbourne is 7 plus instead of regular 7

### ISSUE THREAD

**Issue by tfemby** [matthuisman/i.mjh.nz#77]
Hi there, just letting you know that channel 1000 of au/Melbourne says that it's 7 when in fact it's showing 7+. Not the biggest issue but this is showing a different channel to the guide and therefore incorrect info.

I'm not familiar enough with IPTV to contribute, nor do I understand how you're generating the m3u's and xmls so I could try to experiment with this, however I just want to see this issue to show correct information.

Thanks if you get around to reading this!

**Comment by tfemby** [comment]
Ahh okay, taking a look around looks like you're grabbing streams from https://7plus.com.au/live-tv?channel-id=Seven and possibly building guides from https://freeview.com.au/tv-guide

Here's the difference between the two. 7Plus Guide (what the m3u is actually playing)
https://i.imgur.com/rGpxtyT.png

While the guide is showing this, which is the FreeView guide.
https://i.imgur.com/jTHI6Cj.png

**Comment by matthuisman** [comment]
is it the rights issue? they are not allowed to stream it?
Does the epg match up after Big Bash stuff?

**Comment by tfemby** [comment]
You might be right about it being a rights issue.

What I found out after downloading the FreeView app and the 7+ app was that the FreeView app doesn't actually host live streams. Freeview seems to mostly just be for on-demand and acts as a guide for digital TV like you said.

What's on digital TV and what 7+ also aren't airing the same thing.

I understand you when saying it's too much work to get that to work haha.Thanks again for the reply and looking into this :)
