### ISSUE TITLE
Plex broken

### ISSUE THREAD

**Issue by frmariam** [matthuisman/i.mjh.nz#78]
I just recently found your lists (great content! thank you very much)
Tried PlutoTV, Plex and SamsungTV.

Plex (US list) is not working (the other 2 are running as expected)
Channels are listed and EPG displayed but only 123Go streams. All others give a "404 stream not reachable"
Tried on OTT Navigator (+Tivimate, as it's featured in TroyPoint.com, which is where I found the list).
No VPN, accessing from Europe

**Comment by frmariam** [comment]
Tried the complete (all) list.
Get all listed channels from all countries, but they don't play

**Comment by Toei79** [comment]
idk if plex but some are geo and , theres somes getting geo sadly
