### ISSUE TITLE
PlutoTV extract is retrieving no channels

### ISSUE THREAD

**Issue by davidmguest** [matthuisman/i.mjh.nz#79]
The PlutoTV extract is returning empty playlist files.
![image](https://github.com/matthuisman/i.mjh.nz/assets/97832183/68fa9f1b-e343-40f2-96e7-556b15da7b14)
The Pluto TV addon for Kodi is also showing 0 channels.
![image](https://github.com/matthuisman/i.mjh.nz/assets/97832183/962b00e8-06c8-4ee0-abbb-68af1bb8ec70)

**Comment by matthuisman** [comment]
https://github.com/matthuisman/slyguy.addons/issues/657
