### ISSUE TITLE
Seeking Canberra local ABC stream

### ISSUE THREAD

**Issue by sportswriter** [matthuisman/i.mjh.nz#8]
Hi - there's a [local ABC stream available via iview](https://iview.abc.net.au/show/abc-act-live-stream) (which has the local news service for Canberra). Is that something that can be included in your Canberra listing?  If it can be included, any tips on how I'd go about finding the required information?

**Comment by matthuisman** [comment]
abc canberra uses Dash Widevine so not really possible sorry
It therefore uses the sydney stream currently
