### ISSUE TITLE
Add new ABC FAST channels

### ISSUE THREAD

**Issue by matthuisman** [matthuisman/i.mjh.nz#82]
ABC Iview.
currently Kangaroo, Doc Martin, Australian Story, Fisk

"Also, I have a feeling there's an extra ABC TV stream there too. The blue ABC TV Live Stream that appears at the very top of the Watch Live category may be the National version of ABC TV with a slightly different schedule. I guess the URL will give it away. Or I'm wrong and it just points to ABC TV NSW..."

**Comment by oismacca** [comment]
ABC is no longer offering any of these new FAST-like channels.

**Comment by matthuisman** [comment]
oh. so this is no longer required? That was easy :)
