### ISSUE TITLE
Issues with the SamsungTVPlus list

### ISSUE THREAD

**Issue by webepg** [matthuisman/i.mjh.nz#9]
Hey,

at first I would like to thank you for your work. It's a pleasure to use your playlists.

To my problem: When I try to watch the SamsungTVPlus from Germany most of the channels don't work with OTT Navigator. I do get http 400 (access denied incorrect key?) errors, sometimes after several attempts a channel starts to play. It is not a geo restrictive thing. PlutoTV works perfectly fine. Do I need to set a special http header or a special client a need to set?

**Comment by matthuisman** [comment]
no idea sorry.

**Comment by webepg** [comment]
Turns out it's the player. With the Televizo app it works like a charm
