### ISSUE TITLE
Samsung TV Plus links for Viasat Explore, History, and Nature?

### ISSUE THREAD

**Issue by fraudiay79** [matthuisman/i.mjh.nz#90]
Have you been able to find the Samsung TV Plus links for Viasat Explore, History, and Nature? They have been added to Samsung TV Plus Channels in Scandinavia

https://www.samsung.com/se/smart-tv/samsung-tv-plus/
https://www.samsung.com/no/smart-tv/samsung-tv-plus/
https://www.samsung.com/dk/smart-tv/samsung-tv-plus/
https://www.samsung.com/fi/smart-tv/samsung-tv-plus/

**Comment by matthuisman** [comment]
my playlists use their android app api to get channel list.
The channels on this app differ to the TV.
Also, this app only available in a few countries.
none of the above have the android app available

you may be able to check / ask this guy :https://forums.whirlpool.net.au/thread/9nk6qzy3
