### ISSUE TITLE
Brisbane EPG - SBS channels appear to be in wrong time zone

### ISSUE THREAD

**Issue by aots74** [matthuisman/i.mjh.nz#91]
I am using your Brisbane epg.xml file in tvheadend. All channels appear to be mapped to the correct time. However SBS channels are all out by -1 hour. I don't believe it's anything to do with time zone settings as all other channels are showing programs at the correct times.

**Comment by matthuisman** [comment]
SBS only broadcasts on their website a single timezone. Ignore your local feeds. Compare the EPG you get with the SBS channels and what is on them

**Comment by aots74** [comment]
thanks mate

**Comment by matthuisman** [comment]
no worries. if they ever add local streams, i can use them. but just have to put up with the National streams for now :)
