### ISSUE TITLE
NL Country

### ISSUE THREAD

**Issue by ChefSpeciale** [matthuisman/i.mjh.nz#94]
Hey Matt,

Is it possible to add NL news channels?, i have all channelid's here:

https://vdapi.samsung.com/tvs/tvpersonalize/api/tvapps/appserver/tvplusApp?country=NL&genre=Nieuws&order=asc&offset=0&size=999

thx:)

**Comment by matthuisman** [comment]
Not unless that country has access to the android mobile app

**Comment by matthuisman** [comment]
no. my samsung playlist are generated from their Samsung TV Android mobile app.
Therefore I can only scrape data for the countries that app is available.

If NL is not one of those countries, i can not add those channels

**Comment by ChefSpeciale** [comment]
thx for reply.

hmm cant check, i dont have any samsung device. And my emulator is not working with arm64-v8a & armeabi-v7a :(

**Comment by matthuisman** [comment]
If your play store doesn't let you install that app in your country, then you have the answer
