### ISSUE TITLE
Add Nine Newcastle, Gold Coast and Northern Rivers feeds to the 9Now Kodi addon (and potentially the all AU IPTV list?)

### ISSUE THREAD

**Issue by CrazyErrorGamer** [matthuisman/i.mjh.nz#95]
Recently, Nine added Nine Northern Rivers, Gold Coast and Newcastle streams to the 9Now app that you can find when your location is in Newcastle, Gold Coast or the Northern Rivers region. 

I am asking if you could add these streams in the 9Now Kodi addon and add a Newcastle, Gold Coast and Northern Rivers region setting. You could also potentially put these streams into the AU IPTV list for those who want integration with their own IPTV apps such as Live Channels etc. (don't think it would make sense to create a whole new Newcastle and Northern Rivers region IPTV list as Nine are currently the only ones providing a regional feed of their channel. You could create a Gold Coast IPTV list if you wanted as both Seven and Nine have Gold Coast feeds of their main channel).

The main benefit of these additions is that these feeds have their own local news (NBN News) and occasionally local programming.

Thanks

(EDIT 17/4/24 - noticed that the Gold Coast also now has a regional stream alongside Newcastle and Northern Rivers.)

**Comment by matthuisman** [comment]
are you able to provide the "region" param for these regions?
You should be able to get it using Chrome web tools

Or, simply visiting the url: https://loc.nine.com.au/

**Comment by CrazyErrorGamer** [comment]
Here are the region parameters:
gld = Gold Coast
nlm = Northern Rivers
new = Newcastle

**Comment by matthuisman** [comment]
hmm. the site still seems to return NSW stream for all of them:
eg.
https://api.9now.com.au/ctv/livestreams?device=ctv_androidtv&streamParams=ctv%2Candroid%2Capp_v6-4-2&region=gcq&offset=0

Any region it doesnt understand reverts to NSW stream

Are you sure their website / app carry these regional streams?
Your not just thinking over the air?

**Comment by CrazyErrorGamer** [comment]
That's strange, yes 9Now definitely now carries these streams on both the mobile apps and the website. I was able to find the region parameters by changing my 9Now postcode and then using a m3u8 extractor extension to find the streams and the region parameters. They are definitely 100% a full feed as they show local ads, local news etc.

**Comment by CrazyErrorGamer** [comment]
Here's the direct live stream links, in case they can be of any help:
Gold Coast: https://9now-livestreams-v2.akamaized.net/prod/simulcast/gcq/ch9/hls/r1/index.m3u8
Northern Rivers: https://9now-livestreams-v2.akamaized.net/prod/simulcast/nlm/ch9/hls/r1/index.m3u8
Newcastle: https://9now-livestreams-v2.akamaized.net/prod/simulcast/new/ch9/hls/r1/index.m3u8

**Comment by matthuisman** [comment]
how do you get the website / app to accept a postcode instead of trying to use IP / GPS?

**Comment by CrazyErrorGamer** [comment]
For it to accept the postcode you need to have your IP set to the same state as where you are trying to get the stream from. 

For example, to get the Gold Coast stream, you'd use a VPN that sets your IP to a QLD IP, then go into the 9Now account settings and change your postcode to a Gold Coast postcode (e.g. 4217).

Same applies to Newcastle and Northern Rivers streams, for which you need a NSW IP and to set your postcode to one that is located in those regions.

Make sure to have GPS off if it is on.

**Comment by CrazyErrorGamer** [comment]
> Please provide foxtel epg

Don't think this is the correct place to ask buddy...

**Comment by matthuisman** [comment]
is it possible to do on there website as well?
sorry im not at home so cant test currently

**Comment by CrazyErrorGamer** [comment]
Yes, it is possible to do on the 9Now website, that's where I was able to do it.
