### ISSUE TITLE
Channel 10 Streams

### ISSUE THREAD

**Issue by ndenham** [matthuisman/i.mjh.nz#98]
I've tested a number of Channel 10 streams from different regions and none of them work. I'm in Brisbane so it shouldn't be a geoblocking issue.

**Comment by matthuisman** [comment]
are you using Kodi?

**Comment by ndenham** [comment]
No testing just using VLC. Is there some peculiarity that requires Kodi?

**Comment by matthuisman** [comment]
They probably blocking vlc user agent. Try setting a different user agent
in vlc. Like a browser user agent
